Write a Python program to print the NumPy version in your system

In [2]:
import numpy as np
print("NumPy version:",np.__version__)

NumPy version: 1.24.3


Write a Python program to reverse an array (first element becomes last)

In [2]:
arr1=np.array([1,2,3,4,5,6])
res=arr1[::-1]
print(res)

[6 5 4 3 2 1]


Write a Python program to convert a list and tuple into arrays

In [4]:
lst1=[1,2,3,4,5]
tup1=(6,7,8,9,10)
arr1=np.array(lst1)
arr2=np.array(tup1)
print(arr1,type(arr1))
print(arr2,type(arr2))

[1 2 3 4 5] <class 'numpy.ndarray'>
[ 6  7  8  9 10] <class 'numpy.ndarray'>


Write a Python program to find common values between two arrays

In [11]:
arr1=np.random.randint(1,5,10)
print('arr1:\n',arr1)
arr2=np.random.randint(1,15,10)
print('arr2:\n',arr2)
res=np.intersect1d(arr1,arr2)
print(res)

arr1:
 [4 4 3 4 4 3 4 1 4 2]
arr2:
 [ 8  4  9  6  2  6  8  2 14  4]
[2 4]


Write a Python program compare two arrays using numpy

In [16]:
arr1=np.random.randint(1,5,10)
print('arr1:\n',arr1)
arr2=np.random.randint(1,5,10)
print('arr2:\n',arr2)
arr3=arr1>arr2
print(arr3)

arr1:
 [3 2 3 3 3 4 2 4 2 1]
arr2:
 [1 3 2 2 1 4 3 3 3 1]
[ True False  True  True  True False False  True False False]


Write a Python program to change the dimension of an array

In [27]:
arr1=np.random.randint(1,5,24).reshape(4,2,3) # 3-dimensional
print('arr1:\n',arr1,'\n')
print('Dimension:',np.ndim(arr1))
arr2=arr1.reshape(4,6) # 2-dimensional
print('arr2:\n',arr2)

arr1:
 [[[1 4 1]
  [2 4 4]]

 [[3 1 1]
  [4 4 3]]

 [[1 4 1]
  [4 1 2]]

 [[2 2 2]
  [4 3 3]]] 

arr2:
 [[1 4 1 2 4 4]
 [3 1 1 4 4 3]
 [1 4 1 4 1 2]
 [2 2 2 4 3 3]]


Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100

In [32]:
arr1=np.arange(1,100)
total=0
for x in arr1:
    if x%3==0 or x%5==0:
        total+=x
print(total)

2318


Write a Python program to convert a NumPy array into Python list structure

In [33]:
arr1=np.random.randint(1,5,10)
print(arr1,type(arr1))
arr2=list(arr1)
print(arr2,type(arr2))

[2 3 2 2 4 4 4 2 1 3] <class 'numpy.ndarray'>
[2, 3, 2, 2, 4, 4, 4, 2, 1, 3] <class 'list'>


Write a Python program to how to add an extra column to a numpy array

In [5]:
arr1=np.random.randint(1,5,10).reshape(2,5)
print('arr1:\n',arr1,'\n')
arr2=np.array([111,222])
print('arr2:\n',arr2,'\n')
arr3=np.hstack((arr1,arr2.reshape(-1,1))) # the array to be added as a new column is given along with reshape(-1,1)
# -1 means that the no of rows are automatically calculated to ensure that the dimensions match with the original array
# 1 means the no of rows
print(arr3)

arr1:
 [[2 1 4 3 3]
 [4 3 1 2 3]] 

arr2:
 [111 222] 

[[  2   1   4   3   3 111]
 [  4   3   1   2   3 222]]


Write a Python program to check whether the numpy array is empty or not

In [13]:
arr1=np.array([])
if np.size(arr1)==0:
    print('array is empty')
else:
    print('array is not empty')

array is empty


How to swap two rows of an array? 

In [22]:
arr1=np.random.randint(1,5,12).reshape(4,3) # 3-dimensional
print('arr1:\n',arr1,'\n')
arr1[[1,2]]=arr1[[2,1]] # row 1 and row 2 = row 2 and row 1
print(arr1)

arr1:
 [[2 3 4]
 [3 1 1]
 [3 2 2]
 [4 1 2]] 

[[2 3 4]
 [3 2 2]
 [3 1 1]
 [4 1 2]]


 Python program to create a random vector of size 10 and sort it

In [23]:
vector1=np.random.rand(10)
print('Original vector:\n',vector1,'\n')
vector2=np.sort(vector1)
print('Sorted vector:\n',vector2)

Original vector:
 [0.36506019 0.75236523 0.70402362 0.26216324 0.54933997 0.28519621
 0.35540638 0.89131706 0.45112398 0.31629267] 

Sorted vector:
 [0.26216324 0.28519621 0.31629267 0.35540638 0.36506019 0.45112398
 0.54933997 0.70402362 0.75236523 0.89131706]


 Write a Python program to check two random arrays are equal or not

In [25]:
arr1=np.random.randint(1,5,10)
print('arr1:\n',arr1)
arr2=np.random.randint(1,5,10)
print('arr2:\n',arr2)
res=np.array_equal(arr1,arr2)
print(res)

arr1:
 [4 3 3 4 1 3 4 3 2 1]
arr2:
 [2 3 3 3 1 2 3 1 1 4]
False


Write a Python program to add, subtract, multiply, divide arguments element-wise

In [34]:
arr1=np.random.randint(1,5,12).reshape(3,4)
print('arr1:\n',arr1,'\n')
arr2=np.random.randint(5,9,12).reshape(3,4)
print('arr2:\n',arr2)
arradd=arr1+arr2
print('Addition:\n',arradd,'\n')
arrsub=arr1-arr2
print('Subtraction:\n',arrsub,'\n')
arrmul=arr1*arr2
print('Multiplication:\n',arrmul,'\n')
arrdiv=arr1/arr2
print('Division:\n',arrdiv,'\n')

arr1:
 [[3 2 2 4]
 [3 3 3 4]
 [1 3 4 1]] 

arr2:
 [[6 5 7 5]
 [7 5 6 6]
 [6 8 7 8]]
Addition:
 [[ 9  7  9  9]
 [10  8  9 10]
 [ 7 11 11  9]] 

Subtraction:
 [[-3 -3 -5 -1]
 [-4 -2 -3 -2]
 [-5 -5 -3 -7]] 

Multiplication:
 [[18 10 14 20]
 [21 15 18 24]
 [ 6 24 28  8]] 

Division:
 [[0.5        0.4        0.28571429 0.8       ]
 [0.42857143 0.6        0.5        0.66666667]
 [0.16666667 0.375      0.57142857 0.125     ]] 



Write a Python program to get the dates of yesterday, today and tomorrow. 

In [37]:
todaydate=np.datetime64('today')
print("Today's date: ",todaydate)
yesdate=todaydate+np.timedelta64(-1,'D')
print("Yesterday's date: ",yesdate)
tomdate=todaydate+np.timedelta64(1,'D')
print("Tomorrow's date: ",tomdate)

Today's date:  2023-10-27
Yesterday's date:  2023-10-26
Tomorrow's date:  2023-10-28
